### Site Settings ###
title               : Bernard Wo
description         : >-
                      In my spare time, I love to expand my Hilbert space with some highly coherent coffee :coffee:.
                      During other times, I am entangled with my research work on quantum communication.
# url: "https://bernwo.github.io"
# baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : bernwo/bernwo.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji
  - jekyll-scholar

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Kah Jen Wo (Bernard)
  image             : https://avatars.githubusercontent.com/u/53580103
  # behance           : your_username
# dribbble          : your_username
  email             : bernardwu@outlook.my
  # facebook          : your_username
  github            : bernwo
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : kah-jen-wo-762620175
  # medium            : bernwo
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  # twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

scholar:
  last_name: Wo
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: 
  query: "@*"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
